version: '3.8'

services:
  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: 'stock-api'
    ports:
      - '8080:80' 
    depends_on:
      - ghcr.io/ozon-edu-csharp-2021/supply-service
      - ghcr.io/ozon-edu-csharp-2021/emailing-service
      - ghcr.io/ozon-edu-csharp-2021/employees-service
      - merchandise-service

  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    hostname: 'supply-service'

  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: 'emailing-service'

  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: employees-service
  merchandise-service:
    image: 'merchandise-service:latest'
    hostname: 'merchandise-service'